<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\JustyBase.NetezzaDriver\JustyBase.NetezzaDriver.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Fixtures\**\*.nzreplay.gz" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
