<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<IsAotCompatible>true</IsAotCompatible>
	<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	<Title>Pure C# driver for IBM Netezza database</Title>
	<Version>1.9.4</Version>
	<Description>JustyBase.NetezzaDriver is a .NET library for interacting with IBM Netezza Performance Server databases. It provides a set of classes and methods to facilitate database connections, command execution, and data retrieval. Code is is based on nzpy and npgsql</Description>
	<PackageProjectUrl>https://github.com/justybase/JustyBase.NetezzaDriver</PackageProjectUrl>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<RepositoryUrl>https://github.com/justybase/JustyBase.NetezzaDriver</RepositoryUrl>
	<Authors>Krzysztof Duśko</Authors>
	<PackageTags>nps;netezza;ado ado.net;database;sql</PackageTags>
	<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
	 <!--<PackageLicenseFile>LICENSE</PackageLicenseFile>-->
	<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
	<!--<AllowUnsafeBlocks>true</AllowUnsafeBlocks>-->
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
      <InternalsVisibleTo Include="JustyBase.NetezzaDriver.Tests" />
      <InternalsVisibleTo Include="JustyBase.NetezzaDriver.Benchmarks" />
  </ItemGroup>

	<!-- For .NET 8 -->
	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
	</ItemGroup>

	<!-- For .NET 9 -->
	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.7" />
	</ItemGroup>

	<!-- For .NET 10 -->
	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
	</ItemGroup>

</Project>
